/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function greet(name: string) {
    return invoke()<string>("greet", { name })
}

export function fire(url: string, method: string, headers: { [key: string]: string }, parallelRequests: number, durationMs: number) {
    return invoke()<null>("fire", { url,method,headers,parallelRequests,durationMs })
}


